### ISSUE TITLE
Keyboard layout question

### ISSUE THREAD

**Issue by egency** [pdewacht/oberon-risc-emu#10]
Is it possible to alter the layout for the emulator? It seems that the emulator has a hardcoded layout. It seems to not only ignore the OS layout, but the hardware layout too. I have an ISO keyboard and it assumes ANSI. My OS layout is Dvorak also, which is similarly ignored.

How difficult would it be to alter this behaviour?

**Comment by pdewacht** [comment]
This version of the Oberon system only supports QWERTY keyboard layout. To change that, you'd need to change the big table in [Input.Mod](https://www.inf.ethz.ch/personal/wirth/ProjectOberon/Sources/Input.Mod.txt) and then recompile that module.

The emulator doesn't attempt to handle keyboard layout differences. It just passes the keyboard scancodes uninterpreted to the Oberon system. (Scancodes identify which key on a keyboard was pressed, they don't depend on the keyboard layout).

**Comment by egency** [comment]
Cool, thank you! :)
